name: messenger_clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  google_sign_in: ^4.5.9
  shared_preferences: ^0.5.12+4
  random_string: ^2.1.0
  cloud_firestore: ^0.16.0
  provider: ^4.3.3
  image_picker: ^0.6.7+22
  path: ^1.7.0
  path_provider: ^1.6.27
  flutter_screenutil: ^4.0.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
